services:
  gateway:
    extends:
      file: gateway/docker-compose-base.yaml
      service: gateway
    ports:
      - "8080:8080"
  gateway-dapr:
    extends:
      file: gateway/docker-compose-base.yaml
      service: gateway-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  frontend:
    extends:
      file: frontend/docker-compose-base.yaml
      service: frontend
    ports:
      - "4000:80"
    depends_on:
      - keycloak
  frontend-dapr:
    extends:
      file: frontend/docker-compose-base.yaml
      service: frontend-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  catalog:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog
  catalog-db:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog-db
  catalog-dapr:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  wishlist:
    extends:
      file: wishlist/docker-compose-base.yaml
      service: wishlist
  wishlist-db:
    extends:
      file: wishlist/docker-compose-base.yaml
      service: wishlist-db
  wishlist-dapr:
    extends:
      file: wishlist/docker-compose-base.yaml
      service: wishlist-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  shoppingcart:
    extends:
      file: shoppingcart/docker-compose-base.yaml
      service: shoppingcart
  shoppingcart-db:
    extends:
      file: shoppingcart/docker-compose-base.yaml
      service: shoppingcart-db
  shoppingcart-dapr:
    extends:
      file: shoppingcart/docker-compose-base.yaml
      service: shoppingcart-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  notification:
    extends:
      file: notification/docker-compose-base.yaml
      service: notification
  notification-db:
    extends:
      file: notification/docker-compose-base.yaml
      service: notification-db
  notification-dapr:
    extends:
      file: notification/docker-compose-base.yaml
      service: notification-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  user:
    extends:
      file: user/docker-compose-base.yaml
      service: user
  user-db:
    extends:
      file: user/docker-compose-base.yaml
      service: user-db
  user-dapr:
    extends:
      file: user/docker-compose-base.yaml
      service: user-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  keycloak:
    extends:
      file: keycloak/docker-compose-base.yaml
      service: keycloak
    ports:
      - "8081:80"
  keycloak-db:
    extends:
      file: keycloak/docker-compose-base.yaml
      service: keycloak-db
  keycloak-dapr:
    extends:
      file: keycloak/docker-compose-base.yaml
      service: keycloak-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  inventory:
    extends:
      file: inventory/docker-compose-base.yaml
      service: inventory
  inventory-db:
    extends:
      file: inventory/docker-compose-base.yaml
      service: inventory-db
  inventory-mongosetup:
    extends:
      file: inventory/docker-compose-base.yaml
      service: mongosetup
  inventory-dapr:
    extends:
      file: inventory/docker-compose-base.yaml
      service: inventory-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  tax:
    extends:
      file: tax/docker-compose-base.yaml
      service: tax
  tax-db:
    extends:
      file: tax/docker-compose-base.yaml
      service: tax-db
  tax-dapr:
    extends:
      file: tax/docker-compose-base.yaml
      service: tax-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  review:
    extends:
      file: review/docker-compose-base.yaml
      service: review
  review-db:
    extends:
      file: review/docker-compose-base.yaml
      service: review-db
  review-dapr:
    extends:
      file: review/docker-compose-base.yaml
      service: review-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  address:
    extends:
      file: address/docker-compose-base.yaml
      service: address
  address-db:
    extends:
      file: address/docker-compose-base.yaml
      service: address-db
  address-dapr:
    extends:
      file: address/docker-compose-base.yaml
      service: address-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"
  
  discount:
    extends:
      file: discount/docker-compose-base.yaml
      service: discount
  discount-db:
    extends:
      file: discount/docker-compose-base.yaml
      service: discount-db
  discount-dapr:
    extends:
      file: discount/docker-compose-base.yaml
      service: discount-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"
  
  shipment:
    extends:
      file: shipment/docker-compose-base.yaml
      service: shipment
    environment:
      - MISARCH_SHIPMENT_PROVIDER_ENDPOINT=http://localhost/TODO
  shipment-db:
    extends:
      file: shipment/docker-compose-base.yaml
      service: shipment-db
  shipment-dapr:
    extends:
      file: shipment/docker-compose-base.yaml
      service: shipment-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  return:
    extends:
      file: return/docker-compose-base.yaml
      service: return
  return-db:
    extends:
      file: return/docker-compose-base.yaml
      service: return-db
  return-dapr:
    extends:
      file: return/docker-compose-base.yaml
      service: return-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  payment:
    extends:
      file: payment/docker-compose-base.yaml
      service: payment
  payment-db:
    extends:
      file: payment/docker-compose-base.yaml
      service: payment-db
  payment-dapr:
    extends:
      file: payment/docker-compose-base.yaml
      service: payment-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  order:
    extends:
      file: order/docker-compose-base.yaml
      service: order
  order-db:
    extends:
      file: order/docker-compose-base.yaml
      service: order-db
  order-dapr:
    extends:
      file: order/docker-compose-base.yaml
      service: order-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  media:
    extends:
      file: media/docker-compose-base.yaml
      service: media
    ports:
      - 8080:8080
  media-minio:
    extends:
      file: media/docker-compose-base.yaml
      service: media-minio
    ports:
      - 9000:9000
  media-dapr:
    extends:
      file: media/docker-compose-base.yaml
      service: media-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  placement:
    image: daprio/dapr
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"

  dapr-redis:
    image: redis
    command: redis-server --requirepass redis
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "6379:6379"

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:0.67.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - prometheus
      - zipkin-all-in-one

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
volumes:
  catalog-db-data:
  wishlist-db-data:
  redis-data:
  shoppingcart-db-data:
  notification-db-data:
  user-db-data:
  inventory-db-data:
  keycloak-db-data:
  tax-db-data:
  review-db-data:
  address-db-data:
  discount-db-data:
  shipment-db-data:
  return-db-data:
  payment-db-data:
  order-db-data:
  media-minio-data:
