services:
  catalog:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog
  catalog-db:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog-db
  catalog-dapr:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog-dapr
    volumes:
      - "./dapr-config.yaml:/config.yaml"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:0.67.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - prometheus
      - zipkin-all-in-one

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
volumes:
  catalog-db-data: