services:
  gateway:
    extends:
      file: gateway/docker-compose-base.yaml
      service: gateway
    ports:
      - "8080:8080"
  gateway-dapr:
    extends:
      file: gateway/docker-compose-base.yaml
      service: gateway-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  frontend:
    extends:
      file: frontend/docker-compose-base.yaml
      service: frontend
    ports:
      - "4000:80"
  frontend-dapr:
    extends:
      file: frontend/docker-compose-base.yaml
      service: frontend-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  catalog:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog
  catalog-db:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog-db
  catalog-dapr:
    extends:
      file: catalog/docker-compose-base.yaml
      service: catalog-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  wishlist:
    extends:
      file: wishlist/docker-compose-base.yaml
      service: wishlist
  wishlist-db:
    extends:
      file: wishlist/docker-compose-base.yaml
      service: wishlist-db
  wishlist-dapr:
    extends:
      file: wishlist/docker-compose-base.yaml
      service: wishlist-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  shoppingcart:
    extends:
      file: shoppingcart/docker-compose-base.yaml
      service: shoppingcart
  shoppingcart-db:
    extends:
      file: shoppingcart/docker-compose-base.yaml
      service: shoppingcart-db
  shoppingcart-dapr:
    extends:
      file: shoppingcart/docker-compose-base.yaml
      service: shoppingcart-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  notification:
    extends:
      file: notification/docker-compose-base.yaml
      service: notification
  notification-db:
    extends:
      file: notification/docker-compose-base.yaml
      service: notification-db
  notification-dapr:
    extends:
      file: notification/docker-compose-base.yaml
      service: notification-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  user:
    extends:
      file: user/docker-compose-base.yaml
      service: user
  user-db:
    extends:
      file: user/docker-compose-base.yaml
      service: user-db
  user-dapr:
    extends:
      file: user/docker-compose-base.yaml
      service: user-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  keycloak:
    extends:
      file: keycloak/docker-compose-base.yaml
      service: keycloak
  keycloak-db:
    extends:
      file: keycloak/docker-compose-base.yaml
      service: keycloak-db
  keycloak-dapr:
    extends:
      file: keycloak/docker-compose-base.yaml
      service: keycloak-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"

  inventory:
    extends:
      file: inventory/docker-compose-base.yaml
      service: inventory
  inventory-db:
    extends:
      file: inventory/docker-compose-base.yaml
      service: inventory-db
  inventory-mongosetup:
    extends:
      file: inventory/docker-compose-base.yaml
      service: mongosetup
  inventory-dapr:
    extends:
      file: inventory/docker-compose-base.yaml
      service: inventory-dapr
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"
  
  placement:
    image: daprio/dapr
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"

  dapr-redis:
    image: redis
    command: redis-server --requirepass redis
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "6379:6379"

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:0.67.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - prometheus
      - zipkin-all-in-one

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
volumes:
  catalog-db-data:
  wishlist-db-data:
  redis-data:
  shoppingcart-db-data:
  notification-db-data:
  user-db-data:
  inventory-db-data:
  keycloak-db-data:
