services:
  experiment-config:
    extends:
      file: experiment-config/docker-compose-base.yaml
      service: experiment-config
    image: ghcr.io/misarch/experiment-config:main
    ports:
      - "3000:8080"
  experiment-config-dapr:
    extends:
      file: experiment-config/docker-compose-base.yaml
      service: experiment-config-dapr
    image: "daprio/daprd:edge"
    network_mode: "service:experiment-config"
    command:
      [
        "./daprd",
        "--app-id",
        "experiment-config",
        "--app-port",
        "8080",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]
    volumes:
      - "./.dapr/dapr-config.yaml:/config.yaml"
      - "./.dapr/components:/components"
  dapr-redis:
    image: redis
    command: redis-server --requirepass redis
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "6379:6379"

  experiment-executor-frontend:
    extends:
      file: experiment-executor-frontend/docker-compose-base.yaml
      service: experiment-executor-frontend
    image: ghcr.io/misarch/experiment-executor-frontend:main
    ports:
      - "5173:80"
    environment:
      BACKEND_URL: "http://localhost:8888"

  experiment-executor:
    extends:
      file: experiment-executor/docker-compose-base.yaml
      service: experiment-executor
    image: ghcr.io/misarch/experiment-executor:main
    ports:
      - "8888:8888"
    volumes:
      - experiment-executor-data:/home/java/tests
    environment:
      GRAFANA_ADMIN_USER: "admin"
      GRAFANA_ADMIN_PASSWORD: "admin"
      GRAFANA_HOST: "http://grafana:3000"
      EXPERIMENT_EXECUTOR_URL: "http://experiment-executor:8888"
      GATLING_EXECUTOR_HOST: "http://gatling-executor:8889"
      MISARCH_EXPERIMENT_CONFIG_HOST: "http://experiment-config:8080"
      CHAOSTOOLKIT_EXECUTOR_HOST: "http://chaostoolkit-executor:8890"
      INFLUXDB_URL: "http://influxdb:8086/api/v2/write?org=misarch&bucket=gatling&precision=ms"
      INFLUXDB_TOKEN: "my-secret-token"
      STORE_RESULT_DATA_IN_FILES: "false"
      USE_MISARCH_EXPERIMENT_CONFIG: "true"
      IS_KUBERNETES: "false"

  chaostoolkit-executor:
    extends:
      file: chaostoolkit-executor/docker-compose-base.yaml
      service: chaostoolkit-executor
    image: ghcr.io/misarch/chaostoolkit-executor:main
    environment:
      EXPERIMENT_EXECUTOR_URL: "http://experiment-executor:8888"
    ports:
      - "8890:8890"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  gatling-executor:
    extends:
      file: gatling-executor/docker-compose-base.yaml
      service: gatling-executor
    image: ghcr.io/misarch/gatling-executor:main
    ports:
      - "8889:8889"
    environment:
      EXPERIMENT_EXECUTOR_URL: "http://experiment-executor:8888"

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:0.67.0
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - prometheus
      - zipkin-all-in-one
    ports:
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  cadvisor:
    image: ghcr.io/misarch/cadvisor:v0.53.1-fix
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/run/containerd/containerd.sock:/var/run/containerd/containerd.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=misarch
      - DOCKER_INFLUXDB_INIT_BUCKET=gatling
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-secret-token

volumes:
  cadvisor-data:
  influxdb-data:
  grafana-data:
  redis-data:
  experiment-executor-data: